### ISSUE TITLE
crash when opening demo

### ISSUE THREAD

**Issue by 2-www** [gsequencer/gsequencer#64]
i downloaded the demo file from github and tried opening it in the app and it crashes:
```
** (gsequencer:72): CRITICAL **: 11:21:48.654: ags_soundcard_get_delay: assertion 'AGS_IS_SOUNDCARD(soundcard)' failed

** (gsequencer:72): CRITICAL **: 11:21:48.654: ags_soundcard_get_bpm: assertion 'AGS_IS_SOUNDCARD(soundcard)' failed

(gsequencer:72): GLib-GObject-CRITICAL **: 11:21:48.654: g_object_get: assertion 'G_IS_OBJECT (object)' failed
** Message: 11:21:48.707: ags_dssi_bridge.c - load /usr/lib/dssi/xsynth-dssi.so Xsynth DSSI plugin

Thread 1 "gsequencer" received signal SIGSEGV, Segmentation fault.
0x00007ffff7eefb59 in ags_dssi_bridge_load () from /app/lib/libgsequencer.so.0
(gdb) bt
#0  0x00007ffff7eefb59 in ags_dssi_bridge_load () at /app/lib/libgsequencer.so.0
#1  0x00007ffff7ea0deb in ags_machine_util_new_dssi_bridge () at /app/lib/libgsequencer.so.0
#2  0x00007ffff7ed7d4b in ags_simple_file_read_machine () at /app/lib/libgsequencer.so.0
#3  0x00007ffff7ed86bc in ags_simple_file_read_machine_list () at /app/lib/libgsequencer.so.0
#4  0x00007ffff7ed87eb in ags_simple_file_read_window () at /app/lib/libgsequencer.so.0
#5  0x00007ffff7ed8d76 in ags_simple_file_real_read () at /app/lib/libgsequencer.so.0
#6  0x00007ffff7b1543a in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007ffff7b29ff8 in signal_emit_unlocked_R.isra.0 ()
    at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007ffff7b2b3f1 in signal_emit_valist_unlocked ()
    at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#9  0x00007ffff7b313c1 in g_signal_emit_valist ()
    at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#10 0x00007ffff7b31483 in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007ffff7eca120 in ags_simple_file_read () at /app/lib/libgsequencer.so.0
#12 0x00007ffff7eb96f7 in ags_window_load_file_timeout () at /app/lib/libgsequencer.so.0
#13 0x00007ffff6db8c3a in g_timeout_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#14 0x00007ffff6db5d47 in g_main_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007ffff6db7e57 in g_main_context_iterate_unlocked.isra ()
    at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007ffff6db8513 in g_main_context_iteration ()
    at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x00007ffff6f9bb1d in g_application_run () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#18 0x0000555555556d9d in main ()
(gdb) 
```

**Comment by joelkraehemann** [comment]
I am able to reproduce.

**Comment by joelkraehemann** [comment]
The crash happens because XSynth-DSSI plugin is missing.

**Comment by 2-www** [comment]
do i need to install some package?

**Comment by joelkraehemann** [comment]
I provide you a fix.

**Comment by joelkraehemann** [comment]
Fixed by this commit

https://github.com/gsequencer/gsequencer/commit/00470623189e23024881c4b5db9af8137922aeda

**Comment by 2-www** [comment]
thank you
